/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patient_management_system;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import User.getData;
import User.Users;
import Processes.Appointment;
import Processes.Medication;
/**
 *
 * @author Josh
 */
public class SecretaryOrderMedicine_GUI extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentRequest
     */
    public SecretaryOrderMedicine_GUI() {
        initComponents();
        
        
        ArrayList<Medication> reMedicines = new ArrayList<Medication>();
        getData data = new getData();
        try{
        data.readMedicationRequest(reMedicines);
        }
        catch(Exception e) {
        e.printStackTrace();
        }
        
        Object[] aMedicines = reMedicines.toArray();
        
        String medicine_Name = ((Processes.Medication)aMedicines[0]).getMedicine_Name();
        txtMedicine_Name.setText(medicine_Name);
        int quantity = ((Processes.Medication)aMedicines[0]).getQuantity();
        txtQuantity.setText(String.valueOf(quantity));
        String dosage = ((Processes.Medication)aMedicines[0]).getDosage();
        txtDosage.setText(dosage);       
       
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        txtMedicine_Name = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtDosage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Confirm Medicine");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel4.setText("Medicine Name");

        jLabel6.setText("Quantity");

        jLabel7.setText("Dosage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity)
                            .addComponent(txtDosage)
                            .addComponent(txtMedicine_Name, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicine_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSubmit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Secretary_GUI open = new Secretary_GUI();
        open.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        boolean isNotEmpty = false;
        String medicine_Name;
        int quantity;
        String dosage;        
                
        if(txtMedicine_Name != null) {
        medicine_Name = txtMedicine_Name.getText();
        isNotEmpty = true;
        txtMedicine_Name.setText("");
        }
        else{
        medicine_Name = null;
        isNotEmpty = false;
        }
        
        if(txtQuantity != null) {
        quantity = Integer.parseInt(txtQuantity.getText());
        isNotEmpty = true;
        txtQuantity.setText("");
        }
        else{
        quantity = 0;
        isNotEmpty = false;
        }
        
        if(txtDosage != null) {
        dosage = txtDosage.getText();
        isNotEmpty = true;
        txtDosage.setText("");
        }
        else{
        dosage = null;
        isNotEmpty = false;
        }
        
        
       
        if (Boolean.TRUE.equals(isNotEmpty)){
        try{
        BufferedWriter out = new BufferedWriter(new FileWriter("./accounts\\Medication.txt",true));
        out.newLine();
        out.write(medicine_Name);
        out.newLine();
        out.write(quantity);
        out.newLine();
        out.write(dosage);
        out.newLine();            
        
        out.close();
        }
        catch(Exception e) {
        e.printStackTrace();
        }
        ArrayList<Medication> reMedications = new ArrayList<Medication>();
        getData data = new getData();
        try{
        data.readMedicationRequest(reMedications);
        }
        catch(Exception e) {
        e.printStackTrace();
        }
        
        Object[] aMedications = reMedications.toArray();
        
        int length = aMedications.length;
        data.removeMedication (reMedications.get(0),reMedications);
        aMedications = reMedications.toArray();
        aMedications = reMedications.toArray();
        int newLength = aMedications.length;
        if(newLength > 0) {
        
            for (int l = 0; l < newLength; l++) {
        
                medicine_Name = ((Processes.Medication)aMedications[l]).getMedicine_Name();
                quantity = ((Processes.Medication)aMedications[l]).getQuantity();
                dosage = ((Processes.Medication)aMedications[l]).getDosage();
                
                
                
                try{
                BufferedWriter out = new BufferedWriter(new FileWriter("./accounts\\MedicineRequest.txt", false));
                out.newLine();
                out.write(medicine_Name);
                out.newLine();
                out.write(quantity);
                out.newLine();
                out.write(dosage);
                out.newLine();
                             
                
                
                }
                 catch(Exception e) {
                    e.printStackTrace();
                }
                
        }
            
        }
        else{
         try{
                BufferedWriter out = new BufferedWriter(new FileWriter("./accounts\\MedicineRequest.txt", false));
                    out.newLine();
                }
                catch(Exception e){
                    e.printStackTrace();
                }   
        }        
        }
        

    }//GEN-LAST:event_btnSubmitActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDosage;
    private javax.swing.JTextField txtMedicine_Name;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
